- name: Add cron jobs
  cron:
    name="{{ item.name  }}"
    minute="{{ item.minute | default('*') }}"
    day="{{ item.day | default('*') }}"
    weekday="{{ item.weekday | default('*') }}"
    month="{{ item.month | default('*') }}"
    hour="{{ item.hour | default('*') }}"
    job="{{ item.job }}"
    state=present
    special_time="{{ item.special_time | default('*') }}"
    user="{{ item.user | default('*') }}"
  when: cronjobs is defined
  with_items: "{{ cronjobs | default([]) }}"
