- name: Add cron jobs
  cron:
    name="{{ item.key  }}"
    minute="{{ item.value.minute | default('*') }}"
    day="{{ item.value.day | default('*') }}"
    weekday="{{ item.value.weekday | default('*') }}"
    month="{{ item.value.month | default('*') }}"
    hour="{{ item.value.hour | default('*') }}"
    job="{{ item.value.job }}"
    state=present
    special_time="{{ item.value.special_time | default('*') }}"
    user="{{ item.value.user | default('*') }}"
  when: cronjobs is defined
  with_dict: cronjobs | default({})
