- name: Add git configurations
  template:
    src=gitconfig
    dest=~/.gitconfig
    mode=0644
    owner="{{ server_user }}"
    group="{{ server_group }}"
  sudo: yes
  sudo_user: "{{ server_user }}"
  when: gitconfig is defined

- name: Append ssh config for git
  lineinfile:
    dest: "/home/{{ server_user }}/.ssh/config"
    line:  "Host github.com\n  IdentityFile  {{ gitconfig.ssh_key_path }}\n  IdentitiesOnly  yes"
  sudo: yes
  sudo_user: "{{ server_user }}"
  when: (gitconfig is defined and gitconfig.ssh)

- name: Recognize github to download repos
  shell: ssh-keyscan github.com >> ~/.ssh/known_hosts
  sudo: yes
  sudo_user: "{{ server_user }}"
  when: gitconfig is defined

- name: Udpdate to latest git version
  apt_repository:
    repo: deb http://ftp.us.debian.org/debian testing main contrib non-free
    state: present
    update_cache: yes

- name: Ensure git is installed
  apt:
    name=git
    state=present

