- name: Add git configurations
  template:
    src=gitconfig
    dest=~/.gitconfig
    mode=0644
    owner="{{ server_user }}"
    group="{{ server_group }}"
  become: yes
  become_user: "{{ server_user }}"
  when: gitconfig is defined

- name: Append ssh config for git
  lineinfile:
    dest: "/home/{{ server_user }}/.ssh/config"
    line:  "Host github.com\n  IdentityFile  {{ gitconfig.ssh_key_path }}\n  IdentitiesOnly  yes"
  become: yes
  become_user: "{{ server_user }}"
  when: (gitconfig is defined and gitconfig.ssh)

- name: Recognize github to download repos
  shell: ssh-keyscan github.com >> ~/.ssh/known_hosts
  become: yes
  become_user: "{{ server_user }}"
  when: gitconfig is defined
