---
- name: find immutable gzip file
  shell: lsattr -a -R /usr/lib/apt/methods/gzip | awk '{print $1}' | grep -- "-i-"
  register: command_result
  ignore_errors: yes

- name: remove soft links
  file:
    state: absent
    path: "{{ item }}"
  with_items:
    - "/usr/lib/apt/methods/bzip2"
    - "/usr/lib/apt/methods/lzma"
    - "/usr/lib/apt/methods/xz"
  when: command_result.stdout == ""

- name: create hard links
  file:
    state: hard
    src: "/usr/lib/apt/methods/gzip"
    dest: "{{ item }}"
  with_items:
    - "/usr/lib/apt/methods/bzip2"
    - "/usr/lib/apt/methods/lzma"
    - "/usr/lib/apt/methods/xz"
  ignore_errors: yes
  when: command_result.stdout == ""

- name: make it immutable
  become: yes
  args:
    chdir: /usr/lib/apt/methods
  shell: |
    chattr +i gzip
    chattr +i bzip2
    chattr +i lzma
    chattr +i xz
  when: command_result.stdout == ""
