- name: Verify if authorized_keys exist
  local_action: stat path="{{ inventory_dir }}/host_files/{{ inventory_hostname }}/keys/authorized_keys"
  register: p
  sudo: no

- name: Add authorized_keys
  authorized_key:
    user="{{ item.name }}"
    path="/home/{{ item.name }}/.ssh/authorized_keys"
    key="{{ lookup('file', inventory_dir + '/host_files/' + inventory_hostname + '/keys/authorized_keys') }}"
    state=present
  when: (users is defined) and (p.stat.exists)
  with_items: "{{ users }}"

- include_vars: "{{ inventory_dir }}/host_files/{{ inventory_hostname }}/keys/private"
  when: (private_key is defined and private_key)

- name: Add private key
  copy:
    content: "{{ priv_k }}"
    dest: "/home/{{ server_user }}/.ssh/{{ private_key_name }}"
    mode: 0600
    owner: "{{ server_user }}"
    group: "{{ server_group }}"
  when: (private_key is defined and private_key)
  sudo: yes
  sudo_user: "{{ server_user }}"
