- name: Create server_group
  group:
    name="{{ server_group }}"
    state=present
    system=yes

- name: Create server_user
  user:
    name="{{ server_user }}"
    state=present
    group="{{ server_group }}"
    shell=/bin/bash
    createhome=yes

- name: Ensure defined groups are present
  group:
    name="{{ item.group }}"
    system=yes
    state=present
  with_items: "{{ users  | default([]) }}"
  when: users is defined

- name: Ensure defined users are present
  user:
    name="{{ item.name }}"
    state=present
    group="{{ item.group }}"
    shell=/bin/bash
    generate_ssh_key="{{ item.generate_ssh_key }}"
    ssh_key_bits=2048
    ssh_key_file=.ssh/ansible_generated
    createhome=yes
    password="{{ item.password }}"
    groups="{{ item.extra_groups }}"
  with_items: "{{ users | default([]) }}"
  when: users is defined
